stwp {
    keepalive_timeout    20s;
    client_max_body_size 8m;

    proxy_set_header Star-Real-IP $remote_addr;

    upstream api {
        server 127.0.0.1:8091;
        keepalive 8;
    }

    server {
        listen 9090 default_server;
        listen 9490 star default_server;
        server_name localhost;

        tls_certificate     certs/localhost.pem;
        tls_certificate_key certs/localhost.key;

        location = /health {
            return 200 "ok";
        }

        location /api/ {
            proxy_pass moon://api;
        }

        location = /cat.jpg {
            root www;
        }

        # ./stwp_server on its default ports
        location / {
            proxy_pass moon://127.0.0.1:8090;
        }
    }
}
